#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

polybar &
nitrogen --restore &
xrandr --output HDMI-1 --off &
picom --config ~/.config/herbstluftwm/picom.conf &
bash ~/scripts/auto.sh &

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier
MyTerm=kitty
MyBrowser=brave

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-k close
hc keybind $Mod-b spawn $MyBrowser
hc keybind $Mod-Return spawn $MyTerm 
hc keybind $Mod-m spawn ~/.config/herbstluftwm/rofi/launchers/type-2/launcher.sh
# use your $TERMINAL with xterm as fallback

# focusing clients
hc keybind $Mod-n     focus left
hc keybind $Mod-r     focus right
hc keybind $Mod-t     focus up
hc keybind $Mod-d     focus down

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-n     shift left
hc keybind $Mod-Shift-r     shift right
hc keybind $Mod-Shift-t     shift up
hc keybind $Mod-Shift-d     shift down

# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-n       resize left +$resizestep
hc keybind $Mod-Control-r       resize right + $resizestep
hc keybind $Mod-Control-t       resize up +$resizestep
hc keybind $Mod-Control-d       resize down +$resizestep


# tags
tag_names=("text" "web" "terminal" "music")
tag_keys=( {1..4} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-g  use_index +1 --skip-visible
hc keybind $Mod-h  use_index -1 --skip-visible

# layouting
hc keybind $Mod-z remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 horizontal     \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#800000'
hc set frame_border_normal_color '#ffffff'
hc set frame_bg_normal_color '#c1d1f0'
hc set frame_bg_active_color '#ff8533'
hc set frame_border_width 4
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent on
hc set frame_transparent_width 4
hc set frame_gap 4

hc attr theme.title_height 15
hc attr theme.title_when never
hc attr theme.title_font 'Dejavu Sans:pixelsize=12'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_depth 3  # space below the title's baseline
hc attr theme.active.color '#800000'
hc attr theme.normal.color '#FFFFFF'
hc attr theme.inner_width 3
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#800000'
hc attr theme.normal.inner_color '#FFFFFF'
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 4
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule fixedsize floating=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

